#限流和分布式事务还没有完成
server:
  port: 8082
spring:
  application:
    name: order-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lsy
    password: lsy200111
    url: jdbc:mysql://localhost:3306/train?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    hikari:
      connection-timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 4327e1ac-cbaa-4600-9690-620da130e4b2
  data:
    redis: #非主机redis
      host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
      port: 6379
      password: Redis000

  rabbitmq:
    host: 192.168.170.130
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #这个配置是保证消费者会消费消息，自动确认
    listener:
      simple:
        acknowledge-mode: auto

mq:
  pay-result-callback-order-queue: delay_queue
  pay-result-callback-order-exchange: delay
  pay-result-callback-order-routing-key: key_delay
  refund-result-callback-order-queue: refund_queue
  refund-result-callback-order-exchange: refund_delay
  refund-result-callback-order-routing-key: key_refund_delay

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启mybatis日志

